# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-face-recognizer
  labels:
    app: olivetti-face-recognizer
spec:
  replicas: 3                     
  selector:
    matchLabels:
      app: olivetti-face-recognizer
  template:
    metadata:
      labels:
        app: olivetti-face-recognizer
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: face-recognizer
          image: g25ai1035/olivetti-face-recognizer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
